alertmanager:
  config:
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1m
      receiver: 'gmail-notifications'
    receivers:
      - name: 'gmail-notifications'
        email_configs:
          - to: kubeprometheus.alerts@gmail.com
            from: kubeprometheus.alerts@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: kubeprometheus.alerts@gmail.com
            auth_identity: kubeprometheus.alerts@gmail.com
            auth_password: kubeprometheus
            send_resolved: true
    inhibit_rules:
      - source_match:
        severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']