route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'gmail-notifications'
receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: danceboyyaya@gmail.com
    from: danceboyyaya@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: danceboyyaya@gmail.com
    auth_identity: danceboyyaya@gmail.com
    auth_password: sotsnswexlblqcog
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
