# can now use docker compose in root folder
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: apigateway
    networks:
      - AlwaysObservableApplication
    command: python3 -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB=mongodb://mongodb:27017
      - CommentMicroService=commentMicroservice
      - PostMicroService=postMicroservice
      - AuthMicroService=authMicroservice
  mongodb:
    image: mongo:latest
    container_name: mongoContainer
    hostname: MongoDataBase
    networks:
      - AlwaysObservableApplication
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
  
  commentMicroservice:
    build:
      context: .
      dockerfile: microservices/comments_svc/src/Dockerfile
    image: commentmicroservice
    networks:
      - AlwaysObservableApplication
    command: python3 -u comment_server.py
    ports:
      - "5051:5051"
    volumes:
      - .:/commentMicroservice
    environment:
      - DB=mongodb://mongodb:27017
      
  postMicroservice:
    build:
      context: .
      dockerfile: microservices/post_svc/src/Dockerfile
    image: postmicroservice
    networks:
      - AlwaysObservableApplication
    command: python3 -u post_server.py
    ports:
      - "50051:50051"
    volumes:
      - .:/postMicroservice
    environment:
      - DB=mongodb://mongodb:27017
  authMicroservice:
    build:
      context: .
      dockerfile: microservices/auth_svc/src/Dockerfile
    image: authmicroservice
    networks:
      - AlwaysObservableApplication
    command: python3 -u auth_server.py
    ports:
      - "50056:50056"
    volumes:
      - .:/authenticationMicroservice
    environment:
      - DB=mongodb://mongodb:27017
networks:
      AlwaysObservableApplication:
