# can now use docker compose in root folder
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: apigateway
    networks:
      - AlwaysObservableApplication
    command: python3 -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB=mongodb://mongodb:27017
      - CommentMicroService=commentMicroservice
      - PostMicroService=postMicroservice
      - AuthMicroService=authMicroservice
      
  Commentmongodb:
    image: mongo:latest
    container_name: CommentMongoContainer
    hostname: MongoDataBase
    networks:
      - AlwaysObservableApplication
    environment:
      - MONGO_DATA_DIR=/usr/data/commdb
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/commdb
    ports:
      - 27018:27018
    command: mongod --logpath=/dev/null
  
  commentMicroservice:
    build:
      context: .
      dockerfile: microservices/comments_svc/src/Dockerfile
    image: commentmicroservice
    networks:
      - AlwaysObservableApplication
    command: python3 -u comment_server.py
    ports:
      - "5051:5051"
    volumes:
      - .:/commentMicroservice
    environment:
      - DB=Commentmongodb
      
  postMicroservice:
    build:
      context: .
      dockerfile: microservices/post_svc/src/Dockerfile
    image: postmicroservice
    networks:
      - AlwaysObservableApplication
    command: python3 -u post_server.py
    ports:
      - "50051:50051"
    volumes:
      - .:/postMicroservice
    environment:
      - DB=Postmongodb

  Postmongodb:
    image: mongo:latest
    container_name: PostMongoContainer
    hostname: MongoDataBase
    networks:
      - AlwaysObservableApplication
    environment:
      - MONGO_DATA_DIR=/usr/data/postdb
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/postdb
    ports:
      - 27019:27019
    command: mongod --logpath=/dev/null


  authMicroservice:
    build:
      context: .
      dockerfile: microservices/auth_svc/src/Dockerfile
    image: authmicroservice
    networks:
      - AlwaysObservableApplication
    command: python3 -u auth_server.py
    ports:
      - "50056:50056"
    volumes:
      - .:/authenticationMicroservice
    environment:
      - DB=Authmongodb

  Authmongodb:
    image: mongo:latest
    container_name: AuthMongoContainer
    hostname: MongoDataBase
    networks:
      - AlwaysObservableApplication
    environment:
      - MONGO_DATA_DIR=/usr/data/authdb
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/authdb
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
networks:
      AlwaysObservableApplication:
