apiVersion: apps/v1
kind: Deployment
metadata:
    name: postmongodb
    labels:
        app: postmongodb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postmongodb
    template:
        metadata:
            labels:
                app: postmongodb
        spec:
            containers:
                - name: postmongocontainer
                  image: mongo:latest
                  env:
                    - name: MONGO_DATA_DIR
                      value: /usr/data/postdb
                    - name: MONGO_LOG_DIR
                      value: /dev/null
                  ports:
                    - containerPort: 27017
                  imagePullPolicy: Always
                  resources:
                    limits:
                      memory: 512Mi
                      cpu: "1"
                    requests:
                      memory: 256Mi
                      cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
    name: postmongodb
spec:
    selector:
        app: postmongodb
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017