apiVersion: apps/v1
kind: Deployment
metadata:
    name: authmicroservice
    labels:
        app: authmicroservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: authmicroservice
    template:
        metadata:
            labels:
                app: authmicroservice
        spec:
            containers:
                - name: authmicroservice
                  image: chandradharrao/cty_webapp:authmicroservice
                  env:
                    - name: DB
                      value: authmongodb
                  ports:
                    - containerPort: 50056
                    - containerPort: 7299
                  imagePullPolicy: Always
                  resources:
                    limits:
                      memory: 512Mi
                      cpu: "1"
                    requests:
                      memory: 256Mi
                      cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
    name: authmicroservice
spec:
    selector:
        app: authmicroservice
    ports:
        - protocol: TCP
          port: 50056
          targetPort: 50056
