apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: pes1ug19cs280/hpcty:apigateway
          env:
            - name: DB
              value: mongodb://mongodb:27017
            - name: CommentMicroService
              value: commentMicroservice
            - name: PostMicroService
              value: postmicroserivice
            - name: AuthMicroService
              value: authmicroserivice
          ports:
            - containerPort: 5000
            - containerPort: 8011
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
    name: apigateway
spec:
    type: NodePort
    selector:
        app: apigateway
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
          nodePort: 32000
