# change to app folder to use this
version: '3'
services:
  app:
    build: .
    image: inital-build
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB=mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    container_name: mongoContainer
    hostname: MongoDataBase
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null