alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 20s
      group_interval: 4m
      repeat_interval: 4h
      receiver: 'email-receiver'
      routes: []
    receivers:
    - name: 'email-receiver'
      email_configs:
      - to: danceboyyaya@gmail.com
        from: danceboyyaya@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: danceboyyaya@gmail.com
        auth_password: sotsnswexlblqcog